config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'

  root "static_pages#home"
  
  get "/contact", to: "static_pages#contact"
  get "/about", to: "static_pages#about"
  get "/about_me", to: "static_pages#about_me"
  
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  
  resources :projects, only: [:create, :destroy, :new]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :link, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :projects
    
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
  end
    
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :logged_in_user
    
    def new
        @project=Project.new
    end
    
    def create
        @project=current_user.projects.build(project_params)
        if @project.save
            flash[:success]="Project added"
            redirect_to about_me_path
        else
            flash.now[:danger]="Adding project failed"
            render "new"
        end
    end
    
    def destroy
        Project.find(params[:id]).destroy
        @project_to_remove=params[:id]
        flash[:success]="Project removed"
        respond_to do |format|
            format.html { redirect_to about_me_path }
            format.js
        end
    end
    
    private
    
    def project_params
        params.require(:project).permit(:name, :description, :link)
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user=User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to root_path
    else
      flash.now[:danger]="invalid data"
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_path
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end
  
  def about
  end
  
  def about_me
    @projects=Project.all.paginate(page: params[:page])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def full_title(title="")
        base_title="My Homepage"
        if title.empty?
            base_title
        else
            base_title + " | " + title
        end
    end
    
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def log_in(user)
        session[:user_id]=user.id
    end
    
    def logged_in?
        !session[:user_id].nil?
    end
    
    def log_out
        session.delete(:user_id)
    end
    
    def current_user
        @current_user||=User.find_by(id: session[:user_id])
    end
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Created by Robert G.
    </small>
    <nav>
        <ul>
            <li><%= link_to "About the Page", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <% if logged_in? %>
                <li><%= link_to "Logout", logout_path, method: "delete" %></li>
            <% else %>
                <li><%= link_to "Login", login_path %></li>
            <% end %>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar navbar-inverse mynavbar">
    <div class="header">
            <ul class="nav navbar-nav">
                <li><%= link_to "Homepage", root_path %></li>
                <li><%= link_to "About Me", about_me_path %></li>
                <li><%= link_to "Contact", contact_path %></li>
            </ul>
    </div>
</header>

app/views/layouts/_slideshow_container.html.erb
  <div class="slideshow-container">
    
    <div class="mySlidesIn fadeIn">
      <%= image_tag("img_nature_wide.jpg", :style => "width:100%") %>
    </div>
  
    <div class="mySlidesIn fadeIn">
      <%= image_tag("img_fjords_wide.jpg", :style => "width:100%") %>
    </div>
  
    <div class="mySlidesIn fadeIn">
      <%= image_tag("img_mountains_wide.jpg", :style => "width:100%") %>
    </div>
  
    
    <div class="mySlidesOut fadeOut">
      <%= image_tag("img_mountains_wide.jpg", :style => "width:100%") %>
    </div>
    
    <div class="mySlidesOut fadeOut">
      <%= image_tag("img_nature_wide.jpg", :style => "width:100%") %>
    </div>
    
    <div class="mySlidesOut fadeOut">
      <%= image_tag("img_fjords_wide.jpg", :style => "width:100%") %>
    </div>
    
    <div id="slideshow-overlay"> Robert Glowacki </div>
    
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->
  
</head>
<body>
  
  <%= render "layouts/slideshow_container" %>

  <%= render "layouts/header" %>
  <div id="main-body">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
  
  <script>
  var slideIndex = 0;
  showSlides();
  
  function showSlides() {
      var i;
      var slidesIn = document.getElementsByClassName("mySlidesIn");
      var slidesOut = document.getElementsByClassName("mySlidesOut");
      for (i = 0; i < slidesIn.length; i++) {
        slidesIn[i].style.display = "none";
        slidesOut[i].style.display = "none";
      }
      slideIndex++;
      if (slideIndex> slidesIn.length) {
        slideIndex = 1
      }    
      slidesIn[slideIndex-1].style.display = "block";
      slidesOut[slideIndex-1].style.display = "block";
      setTimeout(showSlides, 10000); // Change image every 10 seconds
  }
  </script>

</body>
</html>

app/views/projects/_project.html.erb
<li id="project-<%= project.id %>">
    <span class="name"><%= project.name %></span>
    <span class="desc"><%= project.description %></span>
    <span class="link"><%= link_to "See me somewhere", "http://#{project.link}" %></span>
    <% if logged_in? %>
        <span class="options">
            <%= link_to "Remove", project, remote: true, method: :delete, data: { confirm: "Are you sure?" } %>
            <%= link_to "Edit", "#" %>
        </span>
    <% end %>
</li>

app/views/projects/destroy.js.erb
$("#project-<%= j @project_to_remove %>").remove();

app/views/projects/new.html.erb
<% provide(:title, "Add a project") %>
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@project) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
      
      <%= f.label :link %>
      <%= f.text_field :link, class: 'form-control' %>

      <%= f.submit "Add", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/shared/_projects_list.html.erb
<ol class="projects">
    <%= render @projects %>
</ol>
<%= will_paginate @projects %>

app/views/static_pages/about.html.erb
<% provide(:title, "about") %>

<div class="contrainer-fluid" id="about-container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8" id="about-info">
            <div>
                <h1>About this page</h1>
                stuff tvjkbjfövjböf jgdöfgjdöfgjdöfgjldö fdgjkdfögjö dflkgjdlgj lkdsjljwejwö sewjsdlfjs
                dfgsldfsödkfj djkfsdf jslldk klsdjflskfjselj  ql3kjasljflsh lkhdflvna lskadfj lkdj lsfkj slkdjsl kja a dklfjadflj
                jsjkgslö kjdl asdj aledjwkl  akeflkfj  sdlfkjsl   lkfjslfjew dlfkdjölgdlögj
                sdkfjsdöfjs ödfls dklf eröljewö wö ölsdföl öwöwsöldjöj4ölj 
                dlfjslkdfjlsdfj kjwöerjwö jlöklweörkwök3 rökwököwkfö ödjqhhialkfase4öqpvi udsöjfg 
                skldjflskdjf lsuwplfjasdökfjweritdergkt5izdogdh lsdfjsldfh
            </div>
        <div class="col-md-2"></div>
    </div>
</div>

app/views/static_pages/about_me.html.erb
<% provide(:title, "about me") %>

<div id="about_me-container">
        <div id="about_me-info">
            <div>
                <h1>About Me</h1>
                stuff tvjkbjfövjböf jgdöfgjdöfgjdöfgjldö fdgjkdfögjö dflkgjdlgj lkdsjljwejwö sewjsdlfjs
                dfgsldfsödkfj djkfsdf jslldk klsdjflskfjselj  ql3kjasljflsh lkhdflvna lskadfj lkdj lsfkj slkdjsl kja a dklfjadflj
                jsjkgslö kjdl asdj aledjwkl  akeflkfj  sdlfkjsl   lkfjslfjew dlfkdjölgdlögj
                sdkfjsdöfjs ödfls dklf eröljewö wö ölsdföl öwöwsöldjöj4ölj 
                dlfjslkdfjlsdfj kjwöerjwö jlöklweörkwök3 rökwököwkfö ödjqhhialkfase4öqpvi udsöjfg 
                skldjflskdjf lsuwplfjasdökfjweritdergkt5izdogdh lsdfjsldfh
            </div>
        </div>
        <div id="about_me-pic">
            <%= image_tag("about_me_pic")%>
        </div>
</div>

<div id="cv-container">
    <section class="about-me-dropdown">
        <p><%= link_to "My CV", "#", id: "CV-link" %><b class="caret"></b></p>
        <div id="my-cv">
            my cv
        </div>
    
        <p><%= link_to "My projects ", "#", id: "project-link"%><b class="caret"></b></p>
        <div id="my-projects">
            my projects
            <% if logged_in? %>
                <p><%= link_to "Add a project", new_project_path %></p>
            <% end %>
            <div class="projects_list">
                <%= render "shared/projects_list" %>
            </div>
        </div>
    </section>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "contact") %>

<div class="contrainer-fluid" id="about-container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8" id="about-info">
            <div>
                <h1>Contact</h1>
                stuff tvjkbjfövjböf jgdöfgjdöfgjdöfgjldö fdgjkdfögjö dflkgjdlgj lkdsjljwejwö sewjsdlfjs
                dfgsldfsödkfj djkfsdf jslldk klsdjflskfjselj  ql3kjasljflsh lkhdflvna lskadfj lkdj lsfkj slkdjsl kja a dklfjadflj
                jsjkgslö kjdl asdj aledjwkl  akeflkfj  sdlfkjsl   lkfjslfjew dlfkdjölgdlögj
                sdkfjsdöfjs ödfls dklf eröljewö wö ölsdföl öwöwsöldjöj4ölj 
                dlfjslkdfjlsdfj kjwöerjwö jlöklweörkwök3 rökwököwkfö ödjqhhialkfase4öqpvi udsöjfg 
                skldjflskdjf lsuwplfjasdökfjweritdergkt5izdogdh lsdfjsldfh
            </div>
        <div class="col-md-2"></div>
    </div>
</div>

app/views/static_pages/home.html.erb
<div id="home-container">
        <div id="home-info">
            <div>
                <h1>Home info</h1>
                stuff tvjkbjfövjböf jgdöfgjdöfgjdöfgjldö fdgjkdfögjö dflkgjdlgj lkdsjljwejwö sewjsdlfjs
                dfgsldfsödkfj djkfsdf jslldk klsdjflskfjselj  ql3kjasljflsh lkhdflvna lskadfj lkdj lsfkj slkdjsl kja a dklfjadflj
                jsjkgslö kjdl asdj aledjwkl  akeflkfj  sdlfkjsl   lkfjslfjew dlfkdjölgdlögj
                sdkfjsdöfjs ödfls dklf eröljewö wö ölsdföl öwöwsöldjöj4ölj 
                dlfjslkdfjlsdfj kjwöerjwö jlöklweörkwök3 rökwököwkfö ödjqhhialkfase4öqpvi udsöjfg 
                skldjflskdjf lsuwplfjasdökfjweritdergkt5izdogdh lsdfjsldfh
            </div>
        </div>
        <div id="cv-pic">
            <%= image_tag("cv_pic")%>
        </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>